## WebApplication Type Setting
## 자바 어플리케이션으로 실행할지 웹 애플리케이션으로 실행할지 설정할 수 있는 설정 값
## banner-mode: off 배너 끔 설정
## allow-bean-definition-overriding: true bean overriding 설정
spring:
  main:
    web-application-type: servlet
    banner-mode: off

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy #logback 설정시 다음과 같이 입력해야 함
    url: jdbc:log4jdbc:postgresql://183.101.136.74:5444/postgres #logback 설정시 앞에 jdbc:log4jdbc 붙여야 함
    username: ENC(OBpS+CdaA8IFDkHuMri4HOKUIG8iAAe3)
    password: ENC(zhN+Fs9PuJhRttA2PdbinNJWIt94Qhva)
    tomcat:
      remove-abandoned: true
      remove-abandoned-timeout: 120
      log-abandoned: true
      max-active: 50
      max-idle: 10
      max-wait: 1000
      #validation-query: "select 1"
      #test-on-borrow: true
      #test-on-connect: true
      test-while-idle: true


## Server Setting
server:
  port: 8080

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )